site_name: DAM - Diseño de Interfaces - 2023/24

nav:
  - Proyecto 2ª ev:
    - 'proyectos/proyecto2ev.md'
  - Inicio:
    - 'index.md'
    - 'entorno.md'
  - UD1 Introducción:
    - 'ud1/ud1_intro.md'
  - UD2 Elementos:
    - 'ud2/ud2_1_electron_requisitos.md'
    - 'ud2/ud2_2_primera_app.md'
    - 'ud2/ud2_3_maquetacion.md'
  - UD3 Componentes:
    - 'ud3/ud3_1_componentes_basicos.md'
    - 'ud3/ud3_2_electron_procesos.md'
  - UD4 Componentes avanzados:
    - 'ud4/ud4_1_componentes_avanzados.md'
    - 'ud4/ud4_2_electron_react.md'
    - 'ud4/ud4_3_react-eventos-estados.md'
    - 'ud4/ud4_4_route-store.md'
    - 'ud4/ud4_5_example.md'
  - UD5 Usabilidad y accesibilidad:
    - 'ud5/ud5_1_usabilidad.md'
    - 'ud5/ud5_2_flutter_intro.md'
    - 'ud5/ud5_3_flutter_layout.md'
    - 'ud5/ud5_4_flutter_state.md'
    - 'ud5/ud5_5_flutter_navigation.md'
    - 'ud5/ud5_6_flutter_persistence.md'
    - 'ud5/ud5_7_flutter_http.md'

theme:
  name: material # readthedocs # material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - toc.follow
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: es
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Cambiar a modo oscuro
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Cambiar a modo claro
      primary: teal
      accent: lime
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/jsanvil/din2023

extra_css:
  - stylesheets/bs5_layout.css
  - stylesheets/custom.css

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

# copyright: |
#   &copy; 2023 <a href="https://github.com/jsanvil" target="_blank" rel="noopener">Jacinto Sanchez</a>

plugins:
  - tags
